version: '3.7'
services:
  mongodb_container:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pL=4&)7X-L-+WbU
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db